name: Jest Test

on:
  push:
    branches: [main]
    paths:
      - 'example-app/**'
      - '!**.md'
  pull_request:
    branches: [main]
    paths:
      - 'example-app/**'
      - '!**.md'

jobs:
  quality:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i -g npm@9.6.7
      - run: |
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
      - run: npm ci
      - name: Run Test
        run: npm run test
