name: Check Code Lint and Format with Biome

on:
  push:
    branches: [main]
    paths:
      - 'example-app/**'
      - '!**.md'
  pull_request:
    branches: [main]
    paths:
      - 'example-app/**'
      - '!**.md'

jobs:
  quality:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.8.3
      - name: Run Biome
        run: biome ci --config-path './example-app/biome.jsonc' './example-app/'
